### ISSUE TITLE
Disabled buttons allow tab selection

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-radio#107]
## Describe the bug

Even when a group of radio buttons is `disabled`, a user can still `tab` into the group, and the 1st option is highlighted. This user is NOT allowed to select or move to the next option. 

## To Reproduce
1. Go to https://auro.alaskaair.com/components/auro/radio
2. Tab into the DISABLED radio group example
3. See error

## Expected behavior

Users should NOT be allowed to `tab` into a disabled radio button group.

## Screenshots

![Screen Shot 2023-04-27 at 11 38 07 AM](https://user-images.githubusercontent.com/181089/234961927-d9d46096-d927-4685-8ed1-418e0c9d729d.png)

## Exit criteria 

This issue can be closed once the error has been corrected. Any additional scope e.g. updates or refactors, should be discussed PRIOR to adding scope to this issue.

**Comment by fajar-apri-alaska** [comment]
I think this issue is already fixed in [this commit](e140fba7f8914bbcefbb6d87f1dcccc906cd0e40).
