### ISSUE TITLE
Keyboard accessibility is not working as expected

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-radio#126]
### Please verify the version of auro-radio you have installed

4.5.7

### Please describe the bug

1. Go to https://auro.alaskaair.com/components/auro/radio
2. Start tabbing until you get to first radio group
3. Tab through radio Group
4. See error when only one radio button gets focus before moving to accordion

### Reproducing the error

This issue is reproducible on the Auro docsite

### Expected behavior

All radio options get focus through keyboard

### What browsers are you seeing the problem on?

Chrome

### Exit criteria

All radio options get focus through keyboard

**Comment by Patrick-Daly-AA** [comment]
Working as expected.  Tab is not expected to select between radio options within a group; arrow keys will navigate within a radio group.
