### ISSUE TITLE
auro-radio: boolean checked feature

### ISSUE THREAD

**Issue by zzacal** [AlaskaAirlines/auro-radio#30]
## Is your feature request related to a problem? Please describe.
It is not possible to dynamically change the checked `auro-radio` once the user has clicked one of the options.

## Describe the solution you'd like
Ideally, we should be able to programmatically check and uncheck the button by passing in `checked={someBoolean}`.

## Describe alternatives you've considered
We've looked into, but unable to implement a force rerender of the radio group when we want to change the selection. 

## Additional context
The problem statement has "once the user has clicked" because we are observing an oddity in the behavior, and it may be helpful (maybe not):

We can use the pattern below to set checked radio dynamically by changing the value of `selectedEmail`. This works until we actually use a mouse click on one of the radio buttons.
This happens on Chrome and Edge. I've not tried other browsers
```
  <auro-radio
    data-testid="savedEmailOption"
    id="memberEmail"
    name="memberEmail"
    {...(selectedEmail === emailOption.memberEmail ? {"checked":""} : {})}
    ></auro-radio>
  <auro-radio
    data-testid="otherEmailOption"
    id="otherEmail"
    name="otherEmail"
    {...(selectedEmail === emailOption.otherEmail ? {"checked":""} : {})}
    ></auro-radio>
```

**Comment by blackfalcon** [comment]
Hey @zzacal the `chedcked` feature is already a boolean feature supported with the auro-checkbox. This attribute is set to [reflect](https://github.com/AlaskaAirlines/auro-radio/blob/master/src/auro-radio.js#L35) the state of the DOM. See the [lit docs](https://lit-element.polymer-project.org/guide/properties#reflected-attributes) for how we are supporting this. 

Is there an issue with programmatically adding/removing this attribute or are you asking that this be managed via a different API interface?

**Comment by geoffrich** [comment]
@blackfalcon while you are able to set checked by adding/removing the attribute or setting the property, it doesn't update the underlying `<input>`. See this [CodePen](https://codepen.io/geoff-rich/pen/abJNmNE) -- clicking the button sets `checked` to false for all the auro-radios. You can see the attribute get removed from both the auro-radio and the shadow input, but the shadow input's checked property is still true.

I think this line needs to be `.checked` so the property is updated: https://github.com/AlaskaAirlines/auro-radio/blob/62f6099a283247f5257464f1f43f3ed443d78499/src/auro-radio.js#L120

**Comment by blackfalcon** [comment]
That all makes sense. I wonder if this is an issue with how auro-checkbox-group managed the state of a group. 

Ok, this is a real bug.

**Comment by geoffrich** [comment]
I think it's a property vs attribute thing. Once a user selects a radio, you can't un-check it by removing the attribute. You need to set the checked property to false instead ([CodePen](https://codepen.io/geoff-rich/pen/VwpaBPW?editors=1010)).

Since we're only setting the [boolean attribute](https://lit.dev/docs/templates/expressions/#boolean-attribute-expressions) on the underlying radio with `?checked`, the property of the radio input is not updated, so it does not become un-checked.

**Comment by geoffrich** [comment]
I briefly looked into this, and it's not as simple as adding `.checked`. We also need to update the radio group to detect changes to the checked property (since it doesn't fire an event) and control the group accordingly. Otherwise it can get into an inconsistent state, i.e. multiple radios checked.

**Comment by blackfalcon** [comment]
@geoffrich are we getting into this custom event discussion here as well? 

@zzacal where are you with this? What is the urgency to get this addressed?

**Comment by geoffrich** [comment]
@blackfalcon this shouldn't require changes to how we do events w/ auro-radio. If we allow setting the `checked` property directly, we need some way to detect that in the radio-group, which may require a custom event. It shouldn't need an API overhaul though; should be strictly internal.

**Comment by zzacal** [comment]
@blackfalcon it's not currently blocking us. We achieved a similar look with native html/css. Of course we would much rather use auro. We plan to swap out our current solution for auro-radio as soon as we are able to.

I appreciate y'all looking into this.

**Comment by zzacal** [comment]
@blackfalcon we have an opportunity to do the swap in the next couple of sprints with a change to the words around our usage. Do you have a rough ETA on this fix that I can use to help inform my product owner about timing our work after the change is complete?

thanks so much

**Comment by blackfalcon** [comment]
@zzacal this is high on the list, should be a focus in the upcoming sprint.

**Comment by zzacal** [comment]
@blackfalcon that's awesome. I'll pass the info along to my product manager.

**Comment by blackfalcon** [comment]
@zzacal please add a comment to the PR https://github.com/AlaskaAirlines/auro-radio/pull/45 so that I can look you into the review process.
