### ISSUE TITLE
auro-radio: radio group contents not controlled if children added after connectedCallback

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-radio#32]
## Describe the bug
If child radios are added to the radio-group after connectedCallback has run, the radio-group will not control the checked state of these children.

This is especially an issue in Svelte, which first appends the group (calling connectedCallback), and then appends the children. At the time connectedCallback has run, the children are not in the DOM, so this.items is empty.

Related: https://github.com/AlaskaAirlines/auro-accordion/issues/18

## To Reproduce
Render the following markup inside Svelte:
```html
<auro-radio-group required>
	<span slot="legend">Form label goes here</span>
	<auro-radio id="radio10" label="Yes" name="radioDemoA" value="yes" />
	<auro-radio id="radio11" label="No" name="radioDemoA" value="no" />
	<auro-radio id="radio12" label="Maybe" name="radioDemoA" value="maybe" />
</auro-radio-group>
```

Interact with the radios. You can check multiple and console errors are thrown:

> Uncaught TypeError: this.items[this.index] is undefined

## Expected behavior
The component reacts to additional slotted radios added after connectedCallback has run.

**Comment by jason-capsule42** [comment]
Assigning this to myself and moving into the current sprint as this fix needs to be resolved in order to complete the update of the Svelte demo.
