### ISSUE TITLE
auro-radio-group: choose form legend/title size

### ISSUE THREAD

**Issue by erikalanghauser** [AlaskaAirlines/auro-radio#5]
## Is your feature request related to a problem? Please describe.
We are currently using a heading for the title of our radio-group as we do not want to use the default form legend type size. This causes there to be a large gap of built in space between the title of the radio-group and the radio-group itself.

## Describe the solution you'd like
The ability to choose the form legend size, so that the title is attached to the radio group, in order to not break a11y.

## Describe alternatives you've considered
Ability to still use the headings for the title to the radio-group but add a hidden attribute in the legend to meet a11y needs.

## Additional context
![image](https://user-images.githubusercontent.com/34354487/95612274-01c34780-0a18-11eb-8261-77382dcb4e66.png)

**Comment by blackfalcon** [comment]
I've included @vidalmenAS @sryckman and @shelbyevans on this issue as well as I feel there is a discussion to be had here. 

In the creation of the checkbox and radio button groups, the size of the form label was discussed and a standard was set. @erikalanghauser's request to have more control over the group label is something that can be done technically, but I want to make sure that we are all on the same page with this new direction. 

@erikalanghauser stated that there was no reference to a standard group label in the UI Kit and that concerns me. 

If customization is to be allowed, I feel that we should have restraint on this. E.g. a limit of the different sized applicable and reasons for using those sizes. Not a fan of having free-form access to this allowing for major differences in the way a form looks from screen to screen.

**Comment by shelbyevans** [comment]
I am not totally understanding the specific need for the alternate sizing and I think a comparison would possibly be helpful. I wonder if we should have a meeting to walk through the specific scenarios and see the the two variances before making a decision? Im open to other ideas as well... @vidalmenAS @sryckman ?

**Comment by blackfalcon** [comment]
Meeting is scheduled to review on 10.27. 
@shelbyevans @sryckman @erikalanghauser @vidalmenAS

**Comment by blackfalcon** [comment]
Added `help wanted` tag to this story. Design input is needed to move forward with any alterations to this component to support any new use case.

**Comment by shelbyevans** [comment]
@blackfalcon For clarification- are you looking for final designs with some sort of redlining or are you looking for design approval on the completed component?

**Comment by blackfalcon** [comment]
@shelbyevans when we last left off with that meeting there were a lot of ideas of how to solve for @erikalanghauser issue. What I am looking for is, what are the decisions that came out of that discussion? If this has an impact on the component, what are those impact(s).

**Comment by shelbyevans** [comment]
@blackfalcon hmm... I wasn't on the hook for next steps, but I think there was a decision made and some examples of the change mocked up and then passed to @vidalmenAS at some point? @erikalanghauser or Evelisse (can't find her on github?) are more in the know. If I can help somehow, let me know.

**Comment by blackfalcon** [comment]
This issue has been set to BLOCKED as there are no reported resolutions. If the design as proposed by @erikalanghauser as changed and no longer requires an update to this component, please let me know so that we can close this issue. 

If there is work to be done, please update as to the status of that request so that we can put action items in place.

**Comment by blackfalcon** [comment]
it's been 26 days since I BLOCKED this issue for lack of resolution. Can someone please update here as to where this ended up? 

If there is no action required, please feel free to close this issue.

**Comment by erikalanghauser** [comment]
Flight Change team moved forward using the component and form legend as-is. 

However, I believe we all agreed there there was a benefit to allowing there to be a sm/md/lg form legend size for future use cases. Next step was UI determining what that sm/md/lg would be.

**Comment by blackfalcon** [comment]
Thanks for the feedback @erikalanghauser. Since there are no current action items to take from this issue I am electing to close this issue. 

Once the design team has determined a new UI direction, that would be a great time to open a new issue with the design direction open for discussion with the Auro team and determine a dev strategy.
