### ISSUE TITLE
auro-radio: error prop should be boolean, not string

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-radio#50]
## Is your feature request related to a problem? Please describe.
The error property on `auro-radio` is currently a string. It should be a boolean instead. Error is an on-off state, not a string.

This API currently results in some awkward code, like how our styling hook is based on error equaling the string `"true"`...

https://github.com/AlaskaAirlines/auro-radio/blob/2e894a0af517b633a4b24cbc2b3156cd96487d1d/src/auro-radio.scss#L28-L30

Or how we have to cast `error` to a boolean to set a class...
https://github.com/AlaskaAirlines/auro-radio/blob/2e894a0af517b633a4b24cbc2b3156cd96487d1d/src/auro-radio.js#L116

We also already check it other places like it's a boolean. There could be a bug here, since `error="false"` will set `aria-invalid="true"`, and `error=""` will set `aria-invalid="false"`.
https://github.com/AlaskaAirlines/auro-radio/blob/2e894a0af517b633a4b24cbc2b3156cd96487d1d/src/auro-radio.js#L93-L99

Our [docs](https://github.com/AlaskaAirlines/auro-radio/blob/master/docs/api.md#properties-auro-radio) are also incorrect, because they say that `error` is a boolean. 

The error prop on the group should remain a string, since it's setting a message, not a boolean state.

This might be a breaking change, but it seems unlikely that anyone is setting `error` on the individual radios directly. At minimum we should make sure the group continues setting error correctly. Our API documentation already promises that error is a boolean, so this change could actually fulfill the contract, not break it.

## Describe the solution you'd like
Error behaves as a boolean.

## Additional context
`auro-checkbox` has the same issue. Whatever change we make here should also apply there.

**Comment by blackfalcon** [comment]
Error was set as a string because when `error=""` is present that is what triggers the UI. The expectation is that there is an error message returned with the property. 

See the "Radio group with error" example http://auro.alaskaair.com/components/auro/radio

Error is a `boolean` on the individual radio button element, but it is a `string` on the group per the reason I mentioned above. http://auro.alaskaair.com/components/auro/radio/api

**Comment by geoffrich** [comment]
@blackfalcon I'm not talking about the group error prop. That's an error message and makes sense as a string. Instead, I'm talking about the error prop on the individual auro-radios. It is set as a string, not a boolean as the docs say.

https://github.com/AlaskaAirlines/auro-radio/blob/2e894a0af517b633a4b24cbc2b3156cd96487d1d/src/auro-radio.js#L45-L48

**Comment by blackfalcon** [comment]
> It is set as a string, not a boolean as the docs say.

Yeop, that's an issue. So... I am not seeing this as a `feature` but a `fix`?

**Comment by geoffrich** [comment]
Sure, it can be a fix. At first I classified it as a feature because I thought it might be intentional and a breaking change.

I'm going to be working #33 this afternoon and can include this change in the branch as well.
