### ISSUE TITLE
Error thrown when group initialized in a Svelte app

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-radio#57]
## Describe the bug
When rendered in a Svelte app, the radio-group throws the following error. The error seems to be thrown once for each radio in the group.

```
Uncaught TypeError: this.items[this.index] is undefined
    reset auro-radio-group.js:84
    updated auro-radio.js:88
    performUpdate updating-element.js:574
    _enqueueUpdate updating-element.js:508
    requestUpdateInternal updating-element.js:474
    initialize updating-element.js:326
    initialize lit-element.js:150
    UpdatingElement updating-element.js:90
    LitElement lit-element.js:82
    AuroRadio auro-radio.js:18
    element index.mjs:376
    create lookup.js:25
    create_component index.mjs:1706
    create lookup.js:125
    create Layout-140f89c0.js:3556
    create_component index.mjs:1706
    create lookup.js:178
    init index.mjs:1803
    App lookup.js:262
    createApp main.ts:4
    <anonymous> main.ts:10
```

Here is the line that throws the error: https://github.com/AlaskaAirlines/auro-radio/blob/18a63ff022a2887e6b4902ce9fea91f60d662703/src/auro-radio-group.js#L84

## To Reproduce
1. Render the below markup in a Svelte app
2. See the errors logged in the console

Sample markup: 
```html
<auro-radio-group required>
    <span slot="legend">Form label goes here</span>
    <auro-radio id="radio10" label="Yes" name="radioDemoA" value="yes" />
    <auro-radio id="radio11" label="No" name="radioDemoA" value="no" />
    <auro-radio id="radio12" label="Maybe" name="radioDemoA" value="maybe" />
</auro-radio-group>
```

## Expected behavior
No error is logged.

## Desktop (please complete the following information):
 - OS: windows 10
 - Browser: Firefox
 - Version: auro-radio 1.5.2

## Additional context
The radio functions as expected, there is only an error in the console. However, throwing such an error does mess up our Jest-based tests.

**Comment by blackfalcon** [comment]
I am unable to repro this in the Auro doc site (React) nor the local demo. @geoffrich do you have any insight as to why Svelte is throwing this error?

**Comment by geoffrich** [comment]
I think it's Svelte-specific, yeah. Probably something to do with when the slot content is populated. We've had issues before where Svelte was creating the slot content later than expected, which messed up the component initialization.

I'll dig into this a bit more.
