### ISSUE TITLE
When using Angular initially bound values with a Form Builder are not reflected

### ISSUE THREAD

**Issue by bdahl1** [AlaskaAirlines/auro-radio#68]
## Describe the bug

When using Angular's reactive form builder values set initially are not reflected in the radio button state.

## To Reproduce

1. Set up a vanilla radio group with several options (or grab my [angular demo branch](https://github.com/bdahl1/OrionAngularDemo/tree/add-more-complex-scenarios))
2. Set the value in the code behind with something like `this.fb.group({ myRadio: ['value1']})`
3. Look at the element

```
  <auro-radio-group required formControlName="desert" ngDefaultControl>
    <span slot="legend">Desert</span>
    <auro-radio id="radio10" label="Yes" name="desert" value="yes"></auro-radio>
    <auro-radio id="radio11" label="No" name="desert" value="no"></auro-radio>
    <auro-radio id="radio12" label="Maybe" name="desert" value="maybe"></auro-radio>
  </auro-radio-group>
```

```
    this.formGroup = this.fb.group({
      firstName: ['Person', [Validators.required]],
      middleName: ['', []],
      lastName: ['', [Validators.required]],
      desert: ['no', [Validators.required]],        <---------- This one
    });
```

## Expected behavior

Assuming the value matches something real, it should be set. In reality no value is selected

## Desktop (please complete the following information):
 - OS: Windows
 - Browser Chrome
 - Version 100.0.4896.60 (Official Build) (64-bit)

**Comment by blackfalcon** [comment]
I need some help with this one as this is very specific to the inner workings of Angular. Am I assuming correctly that this is an issue where you want to programmatically setup a radio button set? 

I do not understand the requirements of something like `this.fb.group({ myRadio: ['value1']})` enough to understand why this is not working. What interface is this requiring that we are not providing?
