### ISSUE TITLE
Design release notes and Figma docs on docsite

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-radio#71]
## General Support Request

Upload design release notes and blueprint embed on the docsite.

**Comment by blackfalcon** [comment]
The page in the Auro docsite has a 404 error? 

https://auro.alaskaair.com/components/auro/radio/figma

**Comment by Patrick-Daly-AA** [comment]
For later discussion: Is there significant value to including Figma docs and/or blueprints on the DocsSite?  Desginers don't seem to use it and instead go straight to the source.  Do Engineers use it?  does it make sense to have documentation that is internal only on our external facing doc site?
