### ISSUE TITLE
Disabled radio button border incorrect? 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-radio#79]
## Describe the bug

While addressing some other updates related to radio-buttons, the disabled state UI feels incorrect. 

## To Reproduce
1. Go to https://auro.alaskaair.com/components/auro/radio#:~:text=Disabled%20radio%20group
1. See issue

## Expected behavior

I would expect that the borders for disabled unselected and selected to be the same? 

## Screenshots

<img width="461" alt="Screen Shot 2022-06-10 at 10 54 13 AM" src="https://user-images.githubusercontent.com/181089/173124042-b9fedb76-b887-4fa5-ad2a-d628bd0ff0ac.png">

<img width="713" alt="Screen Shot 2022-06-10 at 10 53 58 AM" src="https://user-images.githubusercontent.com/181089/173124063-d5427a7a-cb54-4628-894a-72546d86db0f.png">

**Comment by leeejune** [comment]
This Figma UI component was created based off what was in the doc site. I agree that it should look the same, but on the doc site the unselected disabled radio button has the darker border. If we can change this, that'd be great!

**Comment by blackfalcon** [comment]
@leeejune please update https://www.figma.com/file/VpUz89Ov6ImBpY5YvzYbZW/Auro-toolkit?node-id=771%3A914 with the correct specs and then I will update the element.

**Comment by blackfalcon** [comment]
@jordanjones243 please review this issue and let me know if you have any questions.
