### ISSUE TITLE
auro-radio-group: option selected feature

### ISSUE THREAD

**Issue by jesussilverioea** [AlaskaAirlines/auro-radio#97]
## Is your feature request related to a problem? Please describe.
Similarly to auro-select or auro-menu, the ability to have the option selected from the auro-radio-group would be very useful. This can be use to make decisions after the user has selected one of the options form the radio-group.

## Describe the solution you'd like
The option to have a property for a selected option on the radio-group.

For instance:

![image](https://user-images.githubusercontent.com/108018885/228378317-fede389a-c9b5-4d08-8245-e7faf627d8ae.png)

In the case of the image, the option "No" would be the option selected.

e.g this is an example of how it is in the auro-select component

![image](https://user-images.githubusercontent.com/108018885/228378977-b54e89ce-2a4a-432d-ba89-5fdf2c3c8f14.png)

**Comment by fajar-apri-alaska** [comment]
Isn't it better to have `selected` or `checked` property instead in the `auro-radio` element, since radio component can only have one selected items in it ?

> A radio group is a set of checkable buttons, known as radio buttons, where no more than one of the buttons can be checked at a time.
(https://www.w3.org/WAI/ARIA/apg/patterns/radio/)

But its fine if we want to make it the same as auro-select implementation.
